@startuml

interface Services {
  + login(workerId: number, name: string): void
  + logout(): void
}

class ProxyService {
  - authService: AuthenticationService
  - status: boolean

  + ProxyService(authService: AuthenticationService)
  + login(workerId: number, name: string): void
  + getStatus()
  + logout(): void
  - checkAccess(): void
}

class AuthenticationService {
  - status: boolean

  + AuthenticationService()
  + login(workerId: number, name: string): void
  + getStatus()
  + logout(): void
}
class Client{

}

Services <|.. ProxyService
Services <|.. AuthenticationService

ProxyService --> AuthenticationService
Client --> Services

@enduml










